spring:
    datasource:
        url: jdbc:mysql://localhost:3306/student_tracker
        username: root
        password: root
    main:
        banner-mode: off # tira o banner do spring quando rodamos
    jpa:
        hibernate:
            ddl-auto: update #APENAS EM PROJETOS SIMPLES!!
            sql: debug
            orm:
                jdbc:
                    bind: trace

loggin:
    leve:
        root: warn